services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080" # Map port 80 on the host to port 8080 in the container
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app # Mount the local directory to the container for development
